import os
import glob
import pandas as pd
import argparse
import xml.etree.ElementTree as ET


def xml_to_csv(path):
    """Iterates through all .xml files (generated by labelImg) in a given directory and combines them in a single Pandas datagrame.

    Parameters:
    ----------
    path : {str}
        The path containing the .xml files
    Returns
    -------
    Pandas DataFrame
        The produced dataframe
    """
    def angle(x):
        #print("enter")
        if x>-0.196349 and x<=0.19634954:
            return 0
        elif x>0.19634954 and x<=0.58904862:
            return 1
        elif x>0.58904862 and x<=0.9817477:
            return 2
        elif x>0.9817477 and x<=1.3744468:
            return 3
        elif x>1.3744468 and x<=1.76714587:
            return 4
        elif x>1.76714587 and x<=2.15984495:
            return 5
        elif x>2.15984495 and x<=2.55254403:
            return 6
        else:
            return 7 


    xml_list = []
    for xml_file in glob.glob(path + '/*.xml'):
        tree = ET.parse(xml_file)
        print("xml_file",xml_file)
        a= xml_file[:-4]
        root = tree.getroot()
        for member in root.findall('object'):
            value = (a+'.jpg',
                    int(root.find('size')[0].text),
                    int(root.find('size')[1].text),
                    member[1].text,
                    int((float(member[5][0].text)-(float(member[5][2].text)/2))),
                    int((float(member[5][1].text)-(float(member[5][3].text)/2))),
                    int((float(member[5][0].text)+(float(member[5][2].text)/2))),
                    int((float(member[5][1].text)+(float(member[5][3].text)/2))),
                    angle(float(member[5][4].text))
                    )
            print(value[0])
            xml_list.append(value)
    column_name = ['filename', 'width', 'height',
                'class', 'xmin', 'ymin', 'xmax', 'ymax','angle' ]
    xml_df = pd.DataFrame(xml_list, columns=column_name)
    return xml_df


def main():
    # Initiate argument parser
    parser = argparse.ArgumentParser(
        description="Sample TensorFlow XML-to-CSV converter")
    parser.add_argument("-i",
                        "--inputDir",
                        help="Path to the folder where the input .xml files are stored",
                        type=str)
    parser.add_argument("-o",
                        "--outputFile",
                        help="Name of output .csv file (including path)", type=str)
    args = parser.parse_args()

    if(args.inputDir is None):
        args.inputDir = os.getcwd()
    if(args.outputFile is None):
        args.outputFile = args.inputDir + "/labels.csv"

    assert(os.path.isdir(args.inputDir))

    xml_df = xml_to_csv(args.inputDir)
    xml_df.to_csv(
        args.outputFile, index=None)
    print('Successfully converted xml to csv.')


if __name__ == '__main__':
    main()
