import os
import glob
import pandas as pd
import math
import argparse
import xml.etree.ElementTree as ET


def xml_to_csv(path):
    """Iterates through all .xml files (generated by labelImg) in a given directory and combines them in a single Pandas datagrame.

    Parameters:
    ----------
    path : {str}
        The path containing the .xml files
    Returns
    -------
    Pandas DataFrame
        The produced dataframe
    """
    def angle(x):
        #print("enter")
        if x>=-0.19634954and x<=0.19634954:
            return 0
        elif x>0.19634954 and x<=0.58904862:
            return 1
        elif x>0.58904862and x<=0.9817477:
            return 2
        elif x>0.9817477 and x<=1.3744468:
            return 3
        elif x>1.3744468 and x<=1.76714587:
            return 4
        elif x>1.76714587 and x<=2.15984495:
            return 5
        elif x>2.15984495 and x<=2.55254403:
            return 6
        else:
            return 7 
    def minmax(x1y1,x2y2,x1y2,x2y1):
        max_x=max(x1y1[0],x2y2[0],x1y2[0],x2y1[0])
        min_x=min(x1y1[0],x2y2[0],x1y2[0],x2y1[0])
        max_y=max(x1y1[1],x2y2[1],x1y2[1],x2y1[1])
        min_y=min(x1y1[1],x2y2[1],x1y2[1],x2y1[1])
        return min_x,max_x,min_y,max_y
    def rotate_point(pointX, pointY, originX, originY, angle):
        theta = [0,-22.5, -45, -67.5, 90, 112.5, -135, 22.5]
        #theta = [0, 90, 135, 45, 157.5, 112.5, 67.5, 22.5]
        #print(angle)
        angle = (theta[angle])
        if angle > 90:
            angle = -(angle-90)
        else:
            angle = angle
        #print(angle)
        angle = (angle*math.pi)/180
        #print(pointX,originX)
        #print(pointY,originY)
        new_x = math.cos(angle) * (pointX-originX) + math.sin(angle) * (pointY-originY) + originX
        new_y = - math.sin(angle) * (pointX-originX) + math.cos(angle) * (pointY-originY) + originY
        #print("new X",new_x)
        #print("new Y",new_y)
        if(new_x < 0):
            new_x = 0
        #elif(new_x>width):
        #   new_x=width
        elif(new_y<0):
            new_y=0
        #elif(new_y>height):
        #   new_y = height
        return int( new_x ), int (new_y)
    xml_list = []
    for xml_file in glob.glob(path + '/*.xml'):
        tree = ET.parse(xml_file)
        print("xml_file",xml_file)
        a= xml_file[:-4]
        #print("a",type(a))
        b=a+'.jpg'
        root = tree.getroot()
        for member in root.findall('object'):
            value = (b,
                    int(root.find('size')[0].text),
                    int(root.find('size')[1].text),
                    member[1].text,
                    int((float(member[5][0].text)-(float(member[5][2].text)/2))),
                    int((float(member[5][1].text)-(float(member[5][3].text)/2))),
                    int((float(member[5][0].text)+(float(member[5][2].text)/2))),
                    int((float(member[5][1].text)+(float(member[5][3].text)/2))),
                    float(member[5][4].text)
                    )
            xml_list.append(value)
    column_name = ['filename', 'width', 'height',
                'class', 'xmin', 'ymin', 'xmax', 'ymax','angle' ]
    xml_df = pd.DataFrame(xml_list, columns=column_name)
    return xml_df


def main():
    # Initiate argument parser
    parser = argparse.ArgumentParser(
        description="Sample TensorFlow XML-to-CSV converter")
    parser.add_argument("-i",
                        "--inputDir",
                        help="Path to the folder where the input .xml files are stored",
                        type=str)
    parser.add_argument("-o",
                        "--outputFile",
                        help="Name of output .csv file (including path)", type=str)
    args = parser.parse_args()

    if(args.inputDir is None):
        args.inputDir = os.getcwd()
    if(args.outputFile is None):
        args.outputFile = args.inputDir + "/labels.csv"

    assert(os.path.isdir(args.inputDir))

    xml_df = xml_to_csv(args.inputDir)
    xml_df.to_csv(
        args.outputFile, index=None)
    print('Successfully converted xml to csv.')


if __name__ == '__main__':
    main()
